# Generated by Django 4.2.5 on 2023-09-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_blog2_book_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog2',
            name='book_title',
        ),
        migrations.AddField(
            model_name='blog2',
            name='image',
            field=models.ImageField(blank=True, default='Ireland.jpg', upload_to='images'),
        ),
    ]
