# Generated by Django 4.2.5 on 2023-09-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_remove_blog2_book_title_blog2_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog2',
            name='image',
            field=models.ImageField(blank=True, default='images/Ireland.jpg', upload_to='images'),
        ),
    ]
